name: verification-service
description: AutoMCP verification service with multiple groups
packages:
  - pydantic>=2.0.0
groups:
  "verification.groups.example_group:ExampleGroup":
    name: example
    description: Basic example group for AutoMCP verification
  "verification.groups.schema_group:SchemaGroup":
    name: schema
    description: Schema validation group for AutoMCP verification
  "verification.groups.timeout_group:TimeoutGroup":
    name: timeout
    description: Timeout testing group for AutoMCP verification
    config:
      default_delay: 0.5
